spring.application.name=booking.api

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db
spring.datasource.username=hotel_user
spring.datasource.password=hotel_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=mysupersecretkeymysupersecretkey123456
jwt.expiration-ms=3600000

app.frontend-url=http://localhost:5174

server.port=8080
